void assert();
void recupCodeuse();
void splitString(String message, char separator, String* data);
void resetCodeuse();
void deplaceRobot();
void assertInit();
void stopRobot();
void avancerdroit(int distanceAParcourir);
void tourner(int angle);
void finMvt();
